"""Constants for the RepRapFirmware integration."""

DOMAIN = "reprapfirmware"

CONF_USE_SSL = "use_ssl"

DEFAULT_NAME = "RepRapFirmware"
DEFAULT_PORT_HTTP = 80
DEFAULT_PORT_HTTPS = 443
DEFAULT_REQUEST_TIMEOUT = 10.0
DEFAULT_REPLY_TIMEOUT = 2.0
DEFAULT_REPLY_POLL_INTERVAL = 0.05
